### PR TITLE
Remove warp_rs9

### LINKED ISSUE #36: Remove `warp_rs9`?
https://github.com/BlueBrain/Atlas-Download-Tools/blob/6c12da67700ac68383d6eed1bc014783eb912cee/src/atldld/sync.py#L523-L532

Is this useful? 

I would remove it because
* I feel like there is legacy source code inside (e.g. using `warp` from `scikit-image`).
* Pollutes the source code
* Assuming it is implemented correctly, is it useful to specify `dataset_id` and `p` and get the closest img (+ apply synchronization to it)? IMO `download_dataset` does something way more meaningful. Given the section images, it finds their `p`and synchronizes.
* It only returns the warped image, however, it does not return the transformation. We IMO is not great in case we want to reuse the same transformation (e.g. on the expression image)

### PR DESCRIPTION
**Pull request by jankrepl**
Closes #36

### CODE REVIEW

**Comment by jankrepl** [comment]
@EmilieDel @Stannislav feel free to review:)

**Review by Stannislav — APPROVED** [review]
`+0 −131` - nice :D

**Review by EmilieDel — APPROVED** [review]
LGTM!

**Comment by jankrepl** [comment]
Great! Feel free to merge:)

**Pull request merged**
